CREATE OR REPLACE TABLE a637m351.endangered(
    id TINYINT NOT NULL AUTO_INCREMENT,
    name CHAR (32) NOT NULL, 
    desc CHAR (256) DEFAULT 'NO DESCRIPTION PROVIDED',
    PRIMARY KEY (name)
);